name: Build Cyber IO when Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Test mod
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Build mod jar
        run: |
          chmod +x gradlew
          ./gradlew :main:deploy

      - name: Upload Cyber-IO jar
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }} Pull Request
          path: main/build/tmp/deploy/*.jar
