name: Release or Update Cyber IO
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Cyber-IO
        run: |
          chmod +x gradlew
          ./gradlew :main:deploy

      - name: Retrieve meta
        id: retrieveMeta
        run: |
          ./gradlew retrieveMeta

      - name: Create release
        if: ${{ steps.retrieveMeta.outputs.tag_exist == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEADER: ${{ steps.retrieveMeta.outputs.header }}
          VERSION: ${{ steps.retrieveMeta.outputs.version }}
        run: |
          gh release create "$VERSION" --title "$HEADER" --notes-file "Info/ReleaseMessage/$VERSION.md" main/build/tmp/deploy/*.jar
      # Since the tag exists, update the release instead
      - name: Update release file
        if: ${{ steps.retrieveMeta.outputs.tag_exist == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.retrieveMeta.outputs.version }}
        run: |
          gh release upload "$VERSION" main/build/tmp/deploy/*.jar --clobber